# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SZt2JD6ZTvKVv-85-GGzoxSWIQdzlwhr
"""

# Paper Web: Analisis Penyaluran Pupuk Bersubsidi

# 📌 Bagian 1: Pendahuluan
from IPython.display import display, Markdown

display(Markdown("""
# Analisis Penyaluran Pupuk Bersubsidi

Analisis ini bertujuan untuk mengevaluasi tren penyaluran pupuk bersubsidi di Indonesia berdasarkan data kabupaten/kota, jenis pupuk, dan tahun. Fokus utamanya adalah melihat volume penyaluran berdasarkan jenis pupuk dan wilayah administratif.

Sumber data: Google Drive - file CSV berjudul `jml_penyaluran_pupuk_bersubsidi__kabupatenkota_data.csv`
"""))

# 📌 Bagian 2: Impor & Tampilkan Data
import pandas as pd
import matplotlib.pyplot as plt
from google.colab import drive
from IPython.display import display

# Mount Google Drive
drive.mount('/content/drive')

# Ganti path ini sesuai lokasi file kamu di Google Drive
file_path = '/content/drive/MyDrive/analitika data/jml_penyaluran_pupuk_bersubsidi__kabupatenkota_data.csv'
df = pd.read_csv(file_path)
display(df.head())

# 📌 Bagian 3: Ringkasan Data
total_per_tahun = df.groupby("tahun")["volume"].sum().reset_index()
total_per_jenis = df.groupby("jenis_pupuk")["volume"].sum().reset_index()
top_kabupaten = df.groupby("nama_kabupaten_kota")["volume"].sum().sort_values(ascending=False).head(10).reset_index()

# Tampilkan tabel ringkasan
display(Markdown("## Ringkasan Data"))
display(Markdown("### Total Penyaluran per Tahun"))
display(total_per_tahun)

display(Markdown("### Total Penyaluran per Jenis Pupuk"))
display(total_per_jenis)

display(Markdown("### Top 10 Kabupaten/Kota dengan Volume Tertinggi"))
display(top_kabupaten)

# 📌 Bagian 4: Visualisasi Data
display(Markdown("## Visualisasi Data"))

# Grafik 1: Total Penyaluran per Tahun
plt.figure(figsize=(8,5))
plt.bar(total_per_tahun["tahun"].astype(str), total_per_tahun["volume"], color='skyblue')
plt.title("Total Penyaluran Pupuk per Tahun")
plt.xlabel("Tahun")
plt.ylabel("Volume (ton)")
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

# Grafik 2: Total per Jenis Pupuk
plt.figure(figsize=(8,5))
plt.bar(total_per_jenis["jenis_pupuk"], total_per_jenis["volume"], color='orange')
plt.title("Total Penyaluran Berdasarkan Jenis Pupuk")
plt.xlabel("Jenis Pupuk")
plt.ylabel("Volume (ton)")
plt.xticks(rotation=45)
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

# Grafik 3: Top 10 Kabupaten/Kota
plt.figure(figsize=(10,6))
plt.barh(top_kabupaten["nama_kabupaten_kota"], top_kabupaten["volume"], color='green')
plt.title("Top 10 Kabupaten/Kota dengan Penyaluran Tertinggi")
plt.xlabel("Volume (ton)")
plt.ylabel("Kabupaten/Kota")
plt.gca().invert_yaxis()
plt.grid(axis='x', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

# 📌 Bagian 5: Kesimpulan
display(Markdown("""
## Kesimpulan
- **Tahun 2022** menunjukkan volume penyaluran tertinggi.
- Jenis pupuk **UREA dan NPK** adalah yang paling banyak disalurkan.
- Kabupaten di Jawa Barat seperti **Indramayu** dan **Garut** mendominasi distribusi terbanyak.
"""))